apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        # CATCH-ALL RULE: Fires on EVERYTHING
        violation[{"msg": msg}] {
          asset := input.review.object
          
          # This will print the exact name the tool uses for your server
          msg := sprintf("DEBUG: I see an asset of type: '%v'", [asset.asset_type])
        }