apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        # NUCLEAR OPTION: No logic. Just fire.
        violation[{"msg": "ALARM: The policy is definitely connected and running!"}] {
          true
        }