apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
              enum: [allowlist, denylist]
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        violation[{"msg": msg}] {
          # 1. Grab the Asset
          asset := input.review.object
          asset.asset_type == "compute.googleapis.com/Instance"

          # 2. Extract Machine Type
          # We use a helper to safely get the data
          full_type := object.get(asset.resource.data, "machineType", "UNKNOWN")
          
          # 3. logic to handle the URL format
          # (Splits "projects/../machineTypes/n2-standard-16" to just "n2-standard-16")
          parts := split(full_type, "/")
          machine_type := parts[count(parts)-1]

          # 4. Define allowed list
          mode := input.parameters.mode
          allowed_types := {t | t := input.parameters.machine_types[_]}
          
          # 5. Check if it is allowed
          check_violation(mode, machine_type, allowed_types)
          
          msg := sprintf("Budget Violation: Machine type '%v' is too expensive!", [machine_type])
        }

        check_violation("allowlist", type, allowed) {
          not allowed[type]
        }

        check_violation("denylist", type, allowed) {
          allowed[type]
        }