apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        # SPY RULE: Fires on everything and prints the name
        violation[{"msg": msg}] {
          asset := input.review.object
          
          # We force it to fail so we can see the output in the logs
          true
          
          # Print the exact name the tool is using
          msg := sprintf("SPY REPORT: I see an asset with type: '%v'", [asset.asset_type])
        }