apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        # MANHUNT RULE: Ignore the type. Find the name.
        violation[{"msg": msg}] {
          asset := input.review.object
          
          # Check if the name contains our server name
          contains(asset.name, "budget-breaker")

          # Print the Type and the Keys so we can finally see the truth
          res := object.get(asset, "resource", {})
          data := object.get(res, "data", {})
          
          msg := sprintf("GOTCHA! Type is: '%v'. Data keys are: %v", [asset.asset_type, object.keys(data)])
        }