apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        # DATA DUMP RULE (Fixed)
        violation[{"msg": msg}] {
          asset := input.review.object
          asset.asset_type == "compute.googleapis.com/Instance"

          # 1. Grab the resource block safely
          # (Renamed variable 'data' to 'res' to avoid syntax error)
          res := object.get(asset, "resource", {})
          
          # 2. Grab the inner data properties
          props := object.get(res, "data", {})
          
          # 3. Print the available keys so we can see if it is "machineType" or "machine_type"
          msg := sprintf("DEBUG: Found Instance! Keys are: %v", [object.keys(props)])
        }