apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        # DATA DUMP RULE
        violation[{"msg": msg}] {
          asset := input.review.object
          asset.asset_type == "compute.googleapis.com/Instance"

          # We found the instance. Now let's try to grab the data safely.
          # We use object.get() so it doesn't crash if the field is missing.
          data := object.get(asset, "resource", {})
          inner_data := object.get(data, "data", {})
          
          # This line forces a violation and prints the keys inside the data object
          # So we can see if it's "machineType" or "machine_type"
          msg := sprintf("DEBUG: Found Instance! Data keys are: %v", [object.keys(inner_data)])
        }