apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        # MANHUNT RULE (Fixed)
        violation[{"msg": msg}] {
          asset := input.review.object
          
          # Check if the name contains our server name
          contains(asset.name, "budget-breaker")

          # 1. Grab the resource block
          res := object.get(asset, "resource", {})
          
          # 2. Grab the inner data properties
          # (Renamed variable 'data' to 'props' to fix the crash)
          props := object.get(res, "data", {})
          
          # 3. Print the findings
          msg := sprintf("GOTCHA! Type is: '%v'. Data keys are: %v", [asset.asset_type, object.keys(props)])
        }