apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        # VIOLATION RULE: Fires on ANY Compute Instance
        violation[{"msg": msg}] {
          asset := input.review.object
          asset.asset_type == "compute.googleapis.com/Instance"
          
          # We are ignoring the machine type logic for now.
          # We just want to prove the Inspector can see the server.
          msg := "DEBUG: I found the server! The plumbing is working."
        }