apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: gcpcomputeinstancemachinetypev1
spec:
  crd:
    spec:
      names:
        kind: GCPComputeInstanceMachineTypeV1
      validation:
        openAPIV3Schema:
          properties:
            mode:
              type: string
            machine_types:
              type: array
              items:
                type: string
  targets:
    - target: validation.gcp.forsetisecurity.org
      rego: |
        package templates.gcp.GCPComputeInstanceMachineTypeV1

        # UNIVERSAL SPY
        # Triggers on EVERYTHING. No if statements. No filters.
        violation[{"msg": msg}] {
          obj := input.review.object

          # Capture the raw Type and Name exactly as Rego sees them
          # We use object.get so it cannot crash even if fields are missing
          type := object.get(obj, "asset_type", "MISSING_TYPE")
          name := object.get(obj, "name", "MISSING_NAME")
          
          # Grab the data block to see where machineType is hiding
          res := object.get(obj, "resource", {})
          props := object.get(res, "data", {})
          keys := object.keys(props)

          # Force the violation and dump the raw data
          msg := sprintf("SPY REPORT: Type=[%v] Name=[%v] DataKeys=%v", [type, name, keys])
        }